[package]
name = "bots-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.4"
once_cell = "1.16.0"
log = "*"
retour = "0.1.0"
rrplug = { path = "../rrplug" }
# rrplug = { git = "https://github.com/catornot/rrplug.git" }

[build-dependencies]
windres = "0.2.2"

[lib]
crate-type = ["cdylib"]
